export enum StoredValue {
  COMPANIES = "companies",
  COMPANIES_IN_EDIT_MODE = "companies-in-edit-mode",
  COMPANY = "company",
  CURRENT_USER = "current-user",
  CURRENT_USER_DATA = "current-user-data",
  FIREBASE_AUTH = "firebase-auth",
  FIREBASE_STORAGE = "firestore-storage",
  FIRESTORE = "firestore",
  MOBILE_OPEN = "mobile-open",
  NAVBAR_SEARCH = "navbar-search",
  ORDER = "order",
  ORDERS = "orders",
  PRICING_TIERS = "pricing-tiers",
  PRODUCT_CODING = "product-coding",
  PRODUCT_CODING_MAP = "product-coding-map",
  PRODUCTS = "products",
  PRODUCTS_IN_EDIT_MODE = "products-in-edit-mode",
  TOOLBAR_BUTTONS = "toolbar-buttons",
  USER = "user",
  USERS = "users",
}
